### ISSUE TITLE
网页显示中文乱码的问题

### ISSUE THREAD

**Issue by lqhsr** [Akagicv/EvilAppleJuice-ESP32-WEB#2]
建议在HTML代码中添加一行<meta charset="UTF-8">，经测试可以解决问题

**Comment by WindowsNoEditor** [comment]
可以参考readme内的这一行，并参考配图设置：
4MB的falsh在烧录时候请选择Huge APP

因为我用xiao esp32c3也是4mb的flash，在使用huge app可以正常烧录使用

**Comment by WindowsNoEditor** [comment]
看错问题了，好的，日后修改一下html

**Comment by lqhsr** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Akagicv/EvilAppleJuice-ESP32-WEB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月25日(星期六) 凌晨0:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Akagicv/EvilAppleJuice-ESP32-WEB] 网页显示中文乱码的问题 (Issue #2)





 
看错问题了，好的，日后修改一下html
