### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by qiyi71w** [Akagicv/EvilAppleJuice-ESP32-WEB#3]
C:\Users\admin\Downloads\EvilAppleJuice-ESP32-WEB-main\AppleJuice-ESP32-Web\AppleJuice-ESP32-Web.ino: In function 'void loop()':
C:\Users\admin\Downloads\EvilAppleJuice-ESP32-WEB-main\AppleJuice-ESP32-Web\AppleJuice-ESP32-Web.ino:165:37: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  165 |     oAdvertisementData.addData(std::string((char*)DEVICES[device_index], 31));
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     std::string {aka std::__cxx11::basic_string<char>}
In file included from C:\Users\admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-alpha2\libraries\BLE\src/BLEServer.h:22,
                 from C:\Users\admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-alpha2\libraries\BLE\src/BLEDevice.h:21,
                 from C:\Users\admin\Downloads\EvilAppleJuice-ESP32-WEB-main\AppleJuice-ESP32-Web\AppleJuice-ESP32-Web.ino:2:
C:\Users\admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-alpha2\libraries\BLE\src/BLEAdvertising.h:36:29: note:   initializing argument 1 of 'void BLEAdvertisementData::addData(String)'
   36 |         void addData(String data);         // Add data to the payload.
      |                      ~~~~~~~^~~~
C:\Users\admin\Downloads\EvilAppleJuice-ESP32-WEB-main\AppleJuice-ESP32-Web\AppleJuice-ESP32-Web.ino:168:37: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  168 |     oAdvertisementData.addData(std::string((char*)SHORT_DEVICES[device_index], 23));
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     std::string {aka std::__cxx11::basic_string<char>}
C:\Users\admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-alpha2\libraries\BLE\src/BLEAdvertising.h:36:29: note:   initializing argument 1 of 'void BLEAdvertisementData::addData(String)'
   36 |         void addData(String data);         // Add data to the payload.
      |                      ~~~~~~~^~~~
C:\Users\admin\Downloads\EvilAppleJuice-ESP32-WEB-main\AppleJuice-ESP32-Web\AppleJuice-ESP32-Web.ino:174:39: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  174 |       oAdvertisementData.addData(std::string((char*)DEVICES[index], 31));
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                       |
      |                                       std::string {aka std::__cxx11::basic_string<char>}
C:\Users\admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-alpha2\libraries\BLE\src/BLEAdvertising.h:36:29: note:   initializing argument 1 of 'void BLEAdvertisementData::addData(String)'
   36 |         void addData(String data);         // Add data to the payload.
      |                      ~~~~~~~^~~~
C:\Users\admin\Downloads\EvilAppleJuice-ESP32-WEB-main\AppleJuice-ESP32-Web\AppleJuice-ESP32-Web.ino:178:39: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  178 |       oAdvertisementData.addData(std::string((char*)SHORT_DEVICES[index], 23));
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                       |
      |                                       std::string {aka std::__cxx11::basic_string<char>}
C:\Users\admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-alpha2\libraries\BLE\src/BLEAdvertising.h:36:29: note:   initializing argument 1 of 'void BLEAdvertisementData::addData(String)'
   36 |         void addData(String data);         // Add data to the payload.
      |                      ~~~~~~~^~~~
C:\Users\admin\Downloads\EvilAppleJuice-ESP32-WEB-main\AppleJuice-ESP32-Web\AppleJuice-ESP32-Web.ino:184:39: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  184 |       oAdvertisementData.addData(std::string((char*)SHORT_DEVICES[2], 23));
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                       |
      |                                       std::string {aka std::__cxx11::basic_string<char>}
C:\Users\admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-alpha2\libraries\BLE\src/BLEAdvertising.h:36:29: note:   initializing argument 1 of 'void BLEAdvertisementData::addData(String)'
   36 |         void addData(String data);         // Add data to the payload.
      |                      ~~~~~~~^~~~
C:\Users\admin\Downloads\EvilAppleJuice-ESP32-WEB-main\AppleJuice-ESP32-Web\AppleJuice-ESP32-Web.ino:187:39: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  187 |       oAdvertisementData.addData(std::string((char*)SHORT_DEVICES[8], 23));
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                       |
      |                                       std::string {aka std::__cxx11::basic_string<char>}
C:\Users\admin\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.0-alpha2\libraries\BLE\src/BLEAdvertising.h:36:29: note:   initializing argument 1 of 'void BLEAdvertisementData::addData(String)'
   36 |         void addData(String data);         // Add data to the payload.
      |                      ~~~~~~~^~~~

exit status 1

Compilation error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'

**Comment by WindowsNoEditor** [comment]
用的啥开发板呢？

**Comment by qiyi71w** [comment]
> 用的啥开发板呢？

合宙的esp32c3经典款

**Comment by WindowsNoEditor** [comment]
我这边买了块编译烧录没问题，是不是开发版选错了或者环境没搭建好？
